### ISSUE TITLE
[Translation] I've translated this repo to korean

### ISSUE THREAD

**Issue by mingrammer** [git-tips/tips#147]
Hi, I'm mingrammer

I've translated these tips to korean and published on my repository

So, please add this to your `README.md` for korean users :D 

Here is my github repository : [https://github.com/mingrammer/git-tips](https://github.com/mingrammer/git-tips) is for 한국어 (korean language)

Thanks for great tips!!

**Comment by hemanth** [comment]
Please send a PR for the same.
