### ISSUE TITLE
English language error

### ISSUE THREAD

**Issue by Strikerlulu** [git-tips/tips#182]
Its showing in another language when i select English... Isn't it available in **English**?

**Comment by multicast** [comment]
It seems like the last commit update readme into Polish.
If you navigate to parent commit and browse files, you should see English version.

**Comment by mbiesiad** [comment]
Thanks for help. I also wanted make an issue for this. It's about PR #180. @hemanth Please, just update a readme with link to the site version (like in previous versions), not all of the file. Thanks!
![pl-version](https://user-images.githubusercontent.com/18367606/78473093-317a5580-773e-11ea-8d71-effe2f4a4f56.png)

Link: https://github.com/mbiesiad/tips
Best wishes

**Comment by mbiesiad** [comment]
Problem resolved, issue could be closed.
