### ISSUE TITLE
Implement doxie

### ISSUE THREAD

**Issue by hemanth** [git-tips/tips#3]
Interested @tomekwi @stoeffel?

**Comment by tomekwi** [comment]
Definitely! I hope I’ll manage to find some time.

**Comment by hemanth** [comment]
Thanks, we must make module that will help use to integrate doxie with ease, maybe `generator-doxie`?

**Comment by tomekwi** [comment]
You mean something like a template?

I’m going to write `doxie.template` soon – a plugin for doxie:

```sh
doxie --template [library|1-liners|doxie|101|…]
```

If it’s not project-specific, we could add `generator` as one of the available templates.

**Comment by hemanth** [comment]
Kool! I have started working on a `doxie` branch, you will be seeing it soon.

**Comment by tomekwi** [comment]
:+1:

**Comment by hemanth** [comment]
@tomekwi Took me 15mins not bad aye? Checkout master now :wink:

**Comment by tomekwi** [comment]
Great! :D 

I’ve just done something a lot less impressive and it also took 15 minutes. Not that good aye? ;) #6

**Comment by hemanth** [comment]
:one: :five: 

I think it will be way faster after we get `doxie --template` :+1:

**Comment by stoeffel** [comment]
I actually think that we don't need `--template` if one wants to use a
template one can always require i.e. lodash and the template in the
renderer script. But I can see that it's convenient:-)

**Comment by hemanth** [comment]
@stoeffel Ain't you on a vacation bro? :cactus:
