### ISSUE TITLE
Add info about how to use doxie

### ISSUE THREAD

**Issue by surfer190** [git-tips/tips#53]
Please add a short description of how to use doxie to create the `README.MD`

**Comment by hemanth** [comment]
Or maybe we need to add to contribution.md ?

**Comment by andyrsmith** [comment]
+1 I would like to contribute but I haven't figured out how to use Doxie with this repo.

**Comment by hemanth** [comment]
It's done, please read the [contribution.md](https://github.com/git-tips/tips/blob/master/contributing.md).
