### ISSUE TITLE
translation in other language?

### ISSUE THREAD

**Issue by ehrudxo** [git-tips/tips#69]
Hi,

I would like to tranlate your tips in Korean.

But I could not find the way of putting translated files.

If you have any policy, let me know.

**Comment by hemanth** [comment]
Thanks for the initiative, feel free to translate.

Things you could do:

- Create a new `tips-<lang>.json` 
- Edit doxie to create `README-<lang>.md`

**Comment by ehrudxo** [comment]
@hemanth thanks a lot!

**Comment by hemanth** [comment]
@ehrudxo If you are interested you may also translate http://git.io/fp-jargons ;)
