### ISSUE TITLE
I make a new vim plugin, and use this tips.json file as an upstream.

### ISSUE THREAD

**Issue by wsdjeg** [git-tips/tips#82]
Hi man:

thanks for share tips about git, I just create a new plugin [vim-cheat](https://github.com/wsdjeg/vim-cheat/). and I use the [json file](https://raw.githubusercontent.com/git-tips/tips/master/tips.json) as an upstream for the git tips.

with this plugin, you can quick view the tips in vim. and here is an PR for implement this feature.

https://github.com/wsdjeg/vim-cheat/pull/3

**Comment by hemanth** [comment]
Nice, do tweet about it and pass the link.

**Comment by wsdjeg** [comment]
@hemanth I post in twitter, here is the link 
https://twitter.com/_wsdjeg_/status/742325301720580096
